

const actionTypes = {
    ERROR: "ERROR",
    SELECT: "SELECT",
    INSERT: "INSERT",

    GET_LABS_LIST: "GET_LABS_LIST",
    GET_PROJECT_STATES_LIST: "GET_PROJECT_STATES_LIST",

    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    TOGGLE_SIDEBAR_SUBMENU: "TOGGLE_SIDEBAR_SUBMENU",
    GET_TABLE_DATA: "GET_TABLE_DATA",
    GOTO: "GOTO",
};

export default actionTypes;
