"use strict";

/**
 * Store keys to selected form values.
 */

export default {
    // Form identifiers
    ALIGNMENTS_INSERT_FORM: "ALIGNMENTS_INSERT_FORM",
    BASECALLINGS_INSERT_FORM: "BASECALLINGS_INSERT_FORM",
    BIOANALYSERS_INSERT_FORM: "BIOANALYSERS_INSERT_FORM",
    BIOANALYSERS_LANES_INSERT_FORM: "BIOANALYSERS_LANES_INSERT_FORM",
    GENOMES_INSERT_FORM: "GENOMES_INSERT_FORM",
    LIBRARIES_INSERT_FORM: "LIBRARIES_INSERT_FORM",
    PEOPLE_INSERT_FORM: "PEOPLE_INSERT_FORM",
    PROJECTS_INSERT_FORM: "PROJECTS_INSERT_FORM",
    SAMPLES_INSERT_FORM: "SAMPLES_INSERT_FORM",
    USER_REQUESTS_INSERT_FORM: "USER_REQUESTS_INSERT_FORM",
    QUERY_PROJECTS_FORM: "QUERY_PROJECTS_FORM",
    RUNS_INSERT_FORM: "RUNS_INSERT_FORM",
    //AdminSubmitForms
    PROJECT_SHARINGS_INSERT_FORM:"PROJECT_SHARINGS_INSERT_FORM",

    // Suffixes (unique within a form)
    suffixes: {
        PROJECTS: "__PROJECTS",
        SAMPLES: "__SAMPLES",
    }
};