"use strict";


export default {
    ALIGNMENTS_INSERT_FORM: "ALIGNMENTS_INSERT_FORM",
    BASECALLINGS_INSERT_FORM: "BASECALLINGS_INSERT_FORM",
    BIOANALYSERS_INSERT_FORM: "BIOANALYSERS_INSERT_FORM",
    BIOANALYSERS_LANES_INSERT_FORM: "BIOANALYSERS_LANES_INSERT_FORM",
    GENOMES_INSERT_FORM: "GENOMES_INSERT_FORM",
    LIBRARIES_INSERT_FORM: "LIBRARIES_INSERT_FORM",
    PEOPLE_INSERT_FORM: "PEOPLE_INSERT_FORM",
    PROJECTS_INSERT_FORM: "PROJECTS_INSERT_FORM",
    SAMPLES_INSERT_FORM: "SAMPLES_INSERT_FORM",
    USER_REQUESTS_INSERT_FORM: "USER_REQUESTS_INSERT_FORM",
    RUNS_INSERT_FORM: "RUNS_INSERT_FORM",

    // Query projects
    QUERY_PROJECTS_FORM: "QUERY_PROJECTS_FORM",
    QUERY_RUNS_FORM: "QUERY_RUNS_FORM",

    // Admin forms
    PROJECT_SHARINGS_INSERT_FORM: "PROJECT_SHARINGS_INSERT_FORM",
    USERS_INSERT_FORM: "USERS_INSERT_FORM",

    // Signup form
    SIGN_UP_FORM: "SIGN_UP_FORM",
    CHANGE_PASSWORD_FORM: "CHANGE_PASSWORD_FORM",

    suffixes: {
        PROJECTS: "__PROJECTS",
        SAMPLES: "__SAMPLES",
    }
};