"use strict";

/**
 * Options dropdown lists are used in several forms, and are the result
 * of the same backend db query. There is no reason to create one entry per form
 * in the store, so the same data is reused of the same store key is used.
 */

export default {

    // primary lists
    INSTRUMENTS: "INSTRUMENTS_OPTIONS",
    LABORATORIES: "LABORATORIES",  // people, but only labs
    LIB_PROTOCOLS: "LIB_PROTOCOLS_OPTIONS",
    LIB_ADAPTERS: "LIB_ADAPTERS_OPTIONS",
    LIB_STATES: "LIB_STATES_OPTIONS",
    FLOWCELL_TYPES: "FLOWCELL_TYPES_OPTIONS",
    MAPPING_TOOLS: "MAPPING_TOOLS_OPTIONS",
    MULTIPLEX_INDEXES: "MULTIPLEX_INDEXES_OPTIONS",
    PEOPLE: "PEOPLE_OPTIONS",
    PIPELINE_ANALYSIS_TYPES: "PIPELINE_ANALYSIS_TYPES_OPTIONS",
    PIPELINE_VERSIONS: "PIPELINE_VERSIONS_OPTIONS",
    PROJECTS: "PROJECTS_OPTIONS",
    PROJECT_ANALYSES: "PROJECT_ANALYSES_OPTIONS",
    PROJECT_STATES: "PROJECT_STATES_OPTIONS",
    QUANTIF_METHODS: "QUANTIF_METHODS_OPTIONS",
    RUNS_LIST: "RUNS_LIST_OPTIONS",
    RUNS_OUTPUT_FOLDERS: "RUNS_OUTPUT_FOLDERS_OPTIONS",
    RUN_TYPES_LENGTHS: "RUN_TYPES_LENGTHS_OPTIONS",
    SAMPLE_TYPES: "SAMPLE_TYPES_OPTIONS",
    SEQUENCING_KIT_VERSIONS: "SEQUENCING_KIT_VERSIONS_OPTIONS",
    SEQUENCING_QUALITIES: "SEQUENCING_QUALITIES_OPTIONS",
    TAXONOMIES: "TAXONOMIES_OPTIONS",
    RUN_TYPES: "RUN_TYPES",
    READ_LENGTHS: "READ_LENGTHS",

    PROJECTS_ALL: "PROJECTS_ALL",
    PROJECTS_HAVING_A_LIBRARY: "PROJECTS_HAVING_A_LIBRARY",
    PROJECTS_HAVING_A_SAMPLE: "PROJECTS_HAVING_A_SAMPLE",
    PROJECTS_HAVING_A_POOL: "PROJECTS_HAVING_A_POOL",

    // secondaryLists
    BASECALLINGS_OUTPUT_FOLDERS_FOR_RUN: "BASECALLINGS_OUTPUT_FOLDERS_FOR_RUN/",
    SAMPLES_FOR_PROJECT: "SAMPLES_FOR_PROJECT/",
    POOLS_FOR_PROJECT: "POOLS_FOR_PROJECT/",
    LIBRAIRIES_FOR_PROJECT: "LIBRAIRIES_FOR_PROJECT/",

    // Query projects
    RUNS: "RUNS",
    SAMPLES_FOR_PROJECTS: "SAMPLES_FOR_PROJECTS",  // samples for a multiple selection of projects (secondary list)
    PROJECTS_AND_SAMPLES_SEARCHED_BY_TERM: "PROJECTS_AND_SAMPLES_SEARCHED_BY_TERM",  // projects+samples that contain a given string
};